POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "name": "fulano",
  "email": "f@gmail.com",
  "password": "12345",
  "passwordConfirmation": "12345"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "f@gmail.com",
  "password": "12345"
}
###
POST http://localhost:3000/api/surveys
Content-Type: application/json
x-access-token: any_token

{
  "question": "new Question",
  "answers": [
    {
      "image": "any_image",
      "answer": "any_answer"
    },
    {
      "answer": "other_answer"
    }
  ]
}

###
GET http://localhost:3000/api/surveys
Content-Type: application/json
x-access-token: any_token

###
PUT http://localhost:3000/api/surveys/620b9350103bdd5a3822a8f5/results
Content-Type: application/json
x-access-token: any_token

{
  "answer": "any_answer"
}

###
GET http://localhost:3000/api/surveys/6217bef62bb529c1528d8b61/results
Content-Type: application/json
x-access-token: any_token
