version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    stdin_open: true
    tty: true
volumes:
  data: